// <auto-generated/>
using KiotaPosts.Client.V1.Public.Characters;
using KiotaPosts.Client.V1.Public.Comics;
using KiotaPosts.Client.V1.Public.Creators;
using KiotaPosts.Client.V1.Public.Events;
using KiotaPosts.Client.V1.Public.Series;
using KiotaPosts.Client.V1.Public.Stories;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V1.Public {
    /// <summary>
    /// Builds and executes requests for operations under \v1\public
    /// </summary>
    public class PublicRequestBuilder : BaseRequestBuilder {
        /// <summary>The characters property</summary>
        public CharactersRequestBuilder Characters { get =>
            new CharactersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The comics property</summary>
        public ComicsRequestBuilder Comics { get =>
            new ComicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The creators property</summary>
        public CreatorsRequestBuilder Creators { get =>
            new CreatorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public EventsRequestBuilder Events { get =>
            new EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The series property</summary>
        public SeriesRequestBuilder Series { get =>
            new SeriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stories property</summary>
        public StoriesRequestBuilder Stories { get =>
            new StoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new PublicRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/public", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new PublicRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/public", rawUrl) {
        }
    }
}
